services:
  Mooc.Courses.application.CourseCreator:
    class: ../../../../../Contexts/Mooc/Courses/application/CourseCreator
    arguments:
      - '@Mooc.Courses.application.CourseRepository'

  Mooc.Courses.application.CourseRepository:
    class: ../../../../../Contexts/Mooc/Courses/infrastructure/persistence/FileCourseRepository
    arguments: []
